"""This module describes the application models, which are ORM objects"""

import uuid

from sqlalchemy import Float
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from wallet_app.database import Base


class Wallet(Base):
    """
    ORM model for a wallet account.

    Represents a wallet account with unique UUID and
    a balance that reflects the amount of money in the wallet.

    Attributes:
        uuid (str): Unique identifier for the wallet account,
        generated by default.
        balance (float): The amount of money in the wallet, defaults to 0.
    """

    __tablename__ = "wallets"
    uuid: Mapped[str] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )
    balance: Mapped[float] = mapped_column(Float, default=0)
