version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  app:
    build: .
    restart: unless-stopped
    command: >
      sh -c "./wait-for-it.sh db:5432 -- alembic upgrade head &&
               uvicorn wallet_app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/wallet_app
    depends_on:
      - db

volumes:
  db_data:
